[package]
name = "global_git_contribution_graph_api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
reqwest = "0.13.2"
serde = {version = "1.0.228", features = ["derive"]}
tokio = {version = "1.49.0", features = ["full"]}
